//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redunDancer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mbIPTextBoxA {
            get {
                return ((string)(this["mbIPTextBoxA"]));
            }
            set {
                this["mbIPTextBoxA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mbIPTextBoxB {
            get {
                return ((string)(this["mbIPTextBoxB"]));
            }
            set {
                this["mbIPTextBoxB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mbMaskTextBoxA {
            get {
                return ((string)(this["mbMaskTextBoxA"]));
            }
            set {
                this["mbMaskTextBoxA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mbMaskTextBoxB {
            get {
                return ((string)(this["mbMaskTextBoxB"]));
            }
            set {
                this["mbMaskTextBoxB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mbGatewayTextBoxA {
            get {
                return ((string)(this["mbGatewayTextBoxA"]));
            }
            set {
                this["mbGatewayTextBoxA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mbGatewayTextBoxB {
            get {
                return ((string)(this["mbGatewayTextBoxB"]));
            }
            set {
                this["mbGatewayTextBoxB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeviceSelectDropDownA {
            get {
                return ((string)(this["DeviceSelectDropDownA"]));
            }
            set {
                this["DeviceSelectDropDownA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeviceSelectDropDownB {
            get {
                return ((string)(this["DeviceSelectDropDownB"]));
            }
            set {
                this["DeviceSelectDropDownB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mbDNS1TextBox {
            get {
                return ((string)(this["mbDNS1TextBox"]));
            }
            set {
                this["mbDNS1TextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mbDNS2TextBox {
            get {
                return ((string)(this["mbDNS2TextBox"]));
            }
            set {
                this["mbDNS2TextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mbTestPingIntervalTextBox {
            get {
                return ((string)(this["mbTestPingIntervalTextBox"]));
            }
            set {
                this["mbTestPingIntervalTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mbMaxPingTextBox {
            get {
                return ((string)(this["mbMaxPingTextBox"]));
            }
            set {
                this["mbMaxPingTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mbTestPingRetryCountTextBox {
            get {
                return ((string)(this["mbTestPingRetryCountTextBox"]));
            }
            set {
                this["mbTestPingRetryCountTextBox"] = value;
            }
        }
    }
}
